name: Nightly Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 3 * * *'

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'
  CONTAINER_RUNTIME: 'docker'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.9"
            image_tag: "nightly"
            from_tag: "latest"
            container_file: "Containerfile.source"
          - python: "3.7"
            pulp_cli: "0.16.0"
            image_tag: "latest"
            from_tag: "latest"
            container_file: "Containerfile"
          - python: "3.6"
            pulp_cli: "0.15.0"
            image_tag: "latest"
            from_tag: "latest"
            container_file: "Containerfile"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Test Dependencies
        run: pip install -r test_requirements.txt
      - name: Install pulp-cli from source
        run: pip install git+https://github.com/pulp/pulp-cli@main
        if: ${{ ! matrix.pulp_cli }}
      - name: Install specific pulp-cli version
        run: pip install pulp_cli==${{ matrix.pulp_cli }}
        if: ${{ matrix.pulp_cli }}
      - name: Install the ostree utility
        run: sudo apt-get install ostree
      - name: Run tests
        env:
          IMAGE_TAG: ${{ matrix.image_tag }}
          FROM_TAG: ${{ matrix.from_tag }}
          CONTAINER_FILE: ${{ matrix.container_file }}
        run: .ci/run_container.sh make test
